name: Build Shop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Build Project
        run: ./gradlew :app:buildDebug

      - name: Generate Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Upload debug Shop apk
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Shop debug bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab
